spring:
  application:
    name: booking

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:booking
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      ddl-auto: create
      hibernate:
        format_sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      group-id: seat-booked
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

scheduler:
  pass-token-size: 50
