spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://ip.ryankang.kro.kr:3306/booking

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: ip.ryankang.kro.kr
      port: 6379
